beatifulbeast/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings  # new
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('sport/', include('sport.urls')),
    path('classtime/', include('classtime.urls')),
    path('offers/', include('offers.urls')),
    path('contact/', include('contact.urls')),
    path('posts/', include('posts.urls')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . views import RegisterView, home
from . import views

# Add the following to the list of previous imports
from django.contrib.auth import views as auth_views
from .views import CustomLoginView  
from .forms import LoginForm

app_name = "home" 

urlpatterns = [
    path('', views.home, name = "home"),
    path('profile', views.profile, name = "profile"),
    path('register', RegisterView.as_view(), name='users-register'),
    path('Common Questions',views.commonquestion, name="Common Questions"),
    # Add this path for login and logout
    path('login', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='home/login.html',authentication_form=LoginForm), name='login'),                             
    path('logout', auth_views.LogoutView.as_view(template_name='home/logout.html'), name='logout'),
    path('profile',views.profile, name='profile'),
    
]

templates/part/footer.html
{% load static %} 

{% block content %}


<html>

<head> 
<!-- /* we took the footer from-> https://codepen.io/slstudios/pen/XbzQVK */     -->
<style>

        
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,500,300,700);

* {
  font-family: Open Sans;
}

/* body{background-color: blue;
} */



/* section {
  width: 100;
  display: inline-block;
  /* change the background in the log in 
  background: rgba(255, 255, 255, 0.123);
  height: 50vh;
  text-align: center;
  font-size: 22px;
  font-weight: 700;
  text-decoration: underline;
} */

.footer-distributed{
    background: rgba(48, 22, 31, 0.308); 
    box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
    box-sizing: border-box;
    width: 100%;
    text-align: left;
    font: bold 16px sans-serif;
    padding: 55px 50px;
}

.footer-distributed .footer-left,
.footer-distributed .footer-center,
.footer-distributed .footer-right{
    display: inline-block;
    vertical-align: top;
}

/* Footer left */

 .footer-distributed .footer-left{
    width: 40%;
} 

/* The company logo */

.footer-distributed h3{
    color:  #ffffff;
    font: normal 36px 'Open Sans', cursive;
    margin: 0;
}

.footer-distributed h3 span{
    color:  lightseagreen;
}

/* Footer links */

.footer-distributed .footer-links{
    color:  #ffffff;
    margin: 20px 0 12px;
    padding: 0;
}

.footer-distributed .footer-links a{
    display:inline-block;
    line-height: 1.8;
  font-weight:400;
    text-decoration: none;
    color:  inherit;
}

.footer-distributed .footer-company-name{
    color:  rgb(255, 255, 255);
    font-size: 14px;
    font-weight: normal;
    margin: 0;
}

/* Footer Center */

.footer-distributed .footer-center{
    width: 35%;
}

.footer-distributed .footer-center i{
    background-color:  #ceb6c4af;
    color: #ffffff;
    font-size: 25px;
    width: 38px;
    height: 38px;
    border-radius: 50%;
    text-align: center;
    line-height: 42px;
    margin: 10px 15px;
    vertical-align: middle;
}

.footer-distributed .footer-center i.fa-envelope{
    font-size: 17px;
    line-height: 38px;
}

.footer-distributed .footer-center p{
    display: inline-block;
    color: #ffffff;
  font-weight:400;
    vertical-align: middle;
    margin:0;
}

.footer-distributed .footer-center p span{
    display:block;
    font-weight: normal;
    font-size:14px;
    line-height:2;
}

.footer-distributed .footer-center p a{
    color:  #ceb6c4af;
    text-decoration: none;;
}

.footer-distributed .footer-links a:before {
  content: "|";
  font-weight:300;
  font-size: 20px;
  left: 0;
  color: #fff;
  display: inline-block;
  padding-right: 5px;
}

.footer-distributed .footer-links .link-1:before {
  content: none;
}

/* Footer Right */

.footer-distributed .footer-right{
    width: 20%;
}

.footer-distributed .footer-company-about{
    line-height: 20px;
    color:  #791286;
    font-size: 13px;
    font-weight: normal;
    margin: 0;
}

.footer-distributed .footer-company-about span{
    display: block;
    color:  #ffffff;
    font-size: 14px;
    font-weight: bold;
    margin-bottom: 20px;
}

.footer-distributed .footer-icons{
    margin-top: 25px;
}

.footer-distributed .footer-icons a{
    display: inline-block;
    width: 35px;
    height: 35px;
    cursor: pointer;  
    background-color:  #ceb6c4af;
    border-radius: 3px;

    font-size: 20px;
    color: #ffffff; text-align: center;
    line-height: 35px;

    margin-right: 3px;
    margin-bottom: 5px;
}

/* If you don't want880e footer to be responsive, remove these media queries */

 @media (max-width: 500px) {

    .footer-distributed{
        font: bold 14px sans-serif;
    }

    .footer-distributed .footer-left,
    .footer-distributed .footer-center,
    .footer-distributed .footer-right{
        display: block;
        width: 100%;
        margin-bottom: 40px;
        text-align: center;
    }

    .footer-distributed .footer-center i{
        margin-left: 0;
    }

}

.footer-links:hover {
    color:rgba(96, 63, 63, 0.308)
    
}


</style>
</head>

<body>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
          <title>Bootstrap</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
      </svg>


<!-- <section>Footer Example 4</section> -->
<footer class="footer-distributed">

            <div class="footer-left">
                <h3>Beautiful<span>Beast</span></h3>
                <p class="footer-links">
                    <a href="{% url 'home:Common Questions'%}" class="link-1">Common Questions</a></p>
                <p class="footer-company-name">Beautiful Beast gym © 2022</p>
            </div>

            <div class="footer-center">

                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>Medina</span> Sultana Road</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>+966.50.303.5000</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:support@company.com">support@company.com</a></p>
                </div>

            </div>

            <div class="footer-right">

                <div class="footer-icons">

                    <!-- <a href="https://www.instagram.com/beautifulbeastclub/"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a> -->

                    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
                        <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/beautifulbeastclub/"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
                        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
                      </ul>
                
                </div>

            </div>

        </footer>
    </body>

        </html>

{% endblock %}

templates/part/header.html
{% load static %}
{% block content %}


 <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title> </title>
  <meta name="description" content="Free Responsive Html5 Css3 Templates | zerotheme.com">
  <meta name="author" content="www.zerotheme.com">
  
  <!-- Mobile Specific Metas
================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  
  <!-- Owl Carousel Assets -->
  <!-- <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"> -->
  <!-- CSS
================================================== -->
  <!-- <link rel="stylesheet" href="{% static 'css/zerogrid.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/menu.css' %}"> -->
  
  <!-- Custom Fonts -->
  <!-- <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

  
  <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/script.js' %}"></script>

	 <div style=' clear: both; text-align:center; position: relative;'>
	   <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
	  </a>
	</div> -->

	  <!-- <script src="js/html5.js"></script>
	  <script src="js/css3-mediaqueries.js"></script> -->

  <head>
   <style>
      body {
      margin: 0;
      font-family: Roboto, -apple-system, 'Helvetica Neue', 'Segoe UI', Arial, sans-serif;
      background-image: url("{% static 'image/W99.png' %}");
      
    }
/* 
    #header2{
      padding-bottom: 30px;

    } */

    .nav-item {
      font-family: "Playfair Display";
	    color: rgb(102, 74, 52);
      letter-spacing: 3px;
      font-size: 4rem;
      font-weight: 400;
      text-shadow: 0 0 1em hsla(320, 100%, 50%, 0.5),
    0 0 0.125em hsla(320, 100%, 60%, 0.5),
    -0.25em -0.125em 0.125em hsla(40, 100%, 60%, 0.125),
    0.25em 0.125em 0.125em hsla(200, 100%, 60%, 0.25);
    
    }
   </style>
</head>
<body>

<div class="header2 bg-success-gradiant">
  <div class="">
  <!-- Header 1 code -->
  <nav class="navbar navbar-expand-lg h2-nav">
      <div class=" pic ">
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'image/white-logo.png' %}"  width="200px" hight="200px" alt="" />
      </div>

<!-- <div class="img-bg">
  <img id="bg"  style="background-image: url('home/image/WEB-HEADER2.png');"> 
</div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header2" aria-controls="header2" aria-expanded="false" aria-label="Toggle navigation"> 
  <span class="icon-menu"></span>
  </button> -->

  <div class="collapse navbar-collapse hover-dropdown" id="header2">
  <ul class="navbar-nav">
  <li class="nav-item dropdown position-relative">
  <a class="nav-link dropdown-toggle" href="#" id="h2-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <i class="icon-arrow-down ml-1 font-12"></i>
  </a>

  <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'sport' %}">Sports</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'posts' %}">Class Time</a></li>
  <!-- <li class="nav-item"><a class="nav-link" href="{% url 'offers' %}">Offers</a></li> -->
  <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
  <!-- </ul> -->
  <!-- <ul class="navbar-nav ml-auto"> -->
  <li class="nav-item active"><a class="nav-link" href="{% url 'home:users-register' %}">Sign Up</a></li>
  <li class="nav-item active"><a class="nav-link" href="{% url 'home:login' %}">Log in</a></li>
  <!-- login part -->
    {% if user.is_authenticated %}    
        <li class="nav-item"><a href="{% url 'home:profile' %}" class="nav-link">Profile</a></li> 
        <li class="nav-item"><a href="{% url 'home:logout' %}" class="nav-link">Logout</a></li> 
    {% else %}
    
    {% endif %}
  
  	</ul>
  </div>
</nav>


  <!-- End Header 1 code -->

  </div>
  </div> 
  
</body>
<!-- <body class="index-page">
<div class="wrap-body"> -->

<!--////////////////////////////////////Header-->
<!-- <---Top Menu---> 
<!-- <div id="cssmenu" >
  <ul>
	 <li class="has-sub"><a href="#"><span>Category</span></a>
		<ul>
		   <li class="has-sub"><a href="#"><span>Item 1</span></a>
			  <ul>
				 <li><a href="#"><span>Sub Item</span></a></li>
				 <li class="last"><a href="#"><span>Sub Item</span></a></li>
			  </ul>
		   </li>
		   <li class="has-sub"><a href="#"><span>Item 2</span></a>
			  <ul>
				 <li><a href="#"><span>Sub Item</span></a></li>
				 <li class="last"><a href="#"><span>Sub Item</span></a></li>
			  </ul>
		   </li>
		</ul>
	 </li> 

	 <li><a href="{% url 'sport' %}"><span>Sport</span></a></li>
	 <li><a href="{% url 'offers' %}"><span>Offers</span></a></li>
	 <li class="last"><a href="{% url 'contact' %}"><span>Contact</span></a></li>
  </ul>

  <div class="col-md-3 text-end">
	  <button type="button" class="btn btn-outline-primary me-2">Login</button>
	  <button type="button" class="btn btn-primary">Sign-up</button>
	</div>
</div>
<header id="header">
  <div class="wrap-header" > -->
	  <!-- <Main Header> -->
	  <!-- <div class="main-header">
		  <div class="zerogrid">
			  <div class="row">
				  <div class="hero-heading">
					  <span>zMountain</span>
					  <div class="tl"></div>
					  <div class="tr"></div>
					  <div class="br"></div>
					  <div class="bl"></div>
				  </div>
				  <div class="heading-text">
					  <h2>Make Your Theme</h2>
					  <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr,<br> sed diam nonumy eirmod tempor </p>
				  </div>
			  </div>
		  </div>
	  </div>
  </div>
</header> -->
<!-- 
<script src="{% static 'js/owl.carousel.js' %}"></script> -->


<!-- <script>
  $(document).ready(function() {
  $("#owl-slide").owlCarousel({
    autoplay:true,
    autoplayTimeout:3000,
    loop: true,
    lazyLoad : true,
    items: 1,
    dots: true,
    stagePadding: 300,
    responsive : {
      0 : {stagePadding: 0},
      600 : {stagePadding: 100},
      900 : {stagePadding: 200},
      1199 : {}
    },
  });
  });
  </script>


<script>
  $(document).ready(function(){
    $(window).resize(function(){
      var width = (window.innerWidth > 0) ? window.innerWidth : screen.width;
      if (width >= '768') { 
        var footerHeight = $('#footer').outerHeight();
        $('#container').css({'marginBottom': footerHeight + 'px'});
      }else{
        $('#container').css({'marginBottom': '0px'});
      }
    });
    $(window).resize();
  });
  
  </script> -->
<!--   
  <script type="text/javascript" src="{% static 'js/validator.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/form-scripts.js' %}"></script> -->
  
  <!-- </div> -->  
 


		   
{% endblock %}
